[server]
Workers = 2000 # 解析数据包协程数
Size = 10 # 滑动窗口大小(分钟)
Rank = 30 # 滑动窗口内的流量排名数
Eth = "\\Device\\NPF_{A71580F4-5312-4FF8-B88B-3D935E2CACB1}" # 网卡名称，替换为自己的网卡名称
#Eth = "em0"
Port = 31415 # WEB监听端口


[notify]
Enable = false # 是否启用通知，true启用
ThresholdValue = 10 # 大流量告警阈值
ThresholdUnit = "GB" # 大流量告警单位，GB或MB
FrequencyThreshold = 10000 # 高频请求告警阈值
WhiteList = ["10.18.1.1", "10.18.1.2"] # 告警忽略白名单IP
Location = "办公网" # 流量镜像服务器位置

[wecom]
Enable = false # 是否启用企业微信通知，true启用
WebHook = "" # 企业微信机器人Webhook地址

[mail]
Enable = false # 是否启用邮件通知，true启用
SmtpHost = "" # SMTP服务器地址
SmtpPort = 25 # SMTP服务器端口
Username = "" # SMTP用户名
Password = "" # SMTP密码
To = "" # 收件人地址
From = "" # 发件人地址
Cc = [""] # 抄送人地址

[kafka]
Enable = false # 是否启用Kafka，true启用
Brokers = ["", "", ""] #brokers集群地址
Topic = "" # topic名称