name: Build and Release (CentOS)

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build in CentOS 7 container
        uses: addnab/docker-run-action@v3
        with:
          image: centos:7
          options: --user root -v ${{ github.workspace }}:/workdir
          run: |
            set -eux
            
            cd /workdir
            ls -la
            cat Makefile
            yum -y install dos2unix
            dos2unix Makefile
            make --version

            cp /etc/yum.repos.d/CentOS-Base.repo /etc/yum.repos.d/CentOS-Base.repo.bak
            curl -o /etc/yum.repos.d/CentOS-Base.repo http://mirrors.aliyun.com/repo/Centos-7.repo
            yum clean all
            yum makecache

            yum -y update
            yum -y install gcc make autoconf automake libtool wget curl flex bison zip \
              mingw64-gcc mingw64-gcc-c++ golang

            export PATH=$PATH:/usr/lib/golang/bin

            make clean
            make all

            mkdir -p release
            cp bin/go-flow release/
            cp config.toml release/
            cd release
            zip -r ../go_flow_linux.zip go-flow config.toml
            cd ..

            mkdir -p release_win
            cp bin/go-flow.exe release_win/
            cp config.toml release_win/
            cd release_win
            zip -r ../go_flow_windows.zip go-flow.exe config.toml
            cd ..

      - name: Upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-packages
          path: |
            go_flow_linux.zip
            go_flow_windows.zip

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            go_flow_linux.zip
            go_flow_windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}