name: Build and Release (CentOS)

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build in CentOS
    runs-on: ubuntu-latest

    container:
      image: centos:7

    steps:
      - name: Fix CentOS yum mirror (Aliyun)
        run: |
          sed -e 's|^mirrorlist=|#mirrorlist=|g' \
              -e 's|^#baseurl=http://mirror.centos.org|baseurl=https://mirrors.aliyun.com|g' \
              -i.bak /etc/yum.repos.d/CentOS-Base.repo
          yum clean all
          yum makecache

      - name: Install system dependencies
        run: |
          yum -y update
          yum -y install gcc make autoconf automake libtool wget curl flex bison zip \
            mingw64-gcc mingw64-gcc-c++ golang

      - name: Set Go environment
        run: |
          echo "export GOROOT=/usr/lib/golang" >> $GITHUB_ENV
          echo "export GOPATH=/go" >> $GITHUB_ENV
          echo "export PATH=$PATH:/usr/lib/golang/bin:/go/bin" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build static binaries for Linux and Windows
        run: |
          make clean
          make all

      - name: Package Linux release
        run: |
          mkdir -p release
          cp bin/go-flow release/
          cp config.toml release/
          cd release
          zip -r go_flow_linux.zip go-flow config.toml
          mv go_flow_linux.zip ../

      - name: Package Windows release
        run: |
          mkdir -p release
          cp bin/go-flow.exe release/
          cp config.toml release/
          cd release
          zip -r go_flow_windows.zip go-flow.exe config.toml
          mv go_flow_windows.zip ../

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            go_flow_linux.zip
            go_flow_windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
